=== ghsmith/hladpb1/hladpb1-imgtDb/src/main/resources/jaxb/imgt/hladpb1HypervariableRegion.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://pathology.emory.edu/hladpb1HypervariableRegion" targetNamespace="http://pathology.emory.edu/hladpb1HypervariableRegion" elementFormDefault="qualified">

	<xs:element name="reagentLots">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="reagentLot" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="reagentLot">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hypervariableRegions"/>
			</xs:sequence>
			<xs:attribute type="xs:byte" name="lotNumber"/>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="hypervariableRegions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hypervariableRegion" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hypervariableRegion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hvrVariants"/>
			</xs:sequence>
			<xs:attribute type="xs:string" name="hvrName" use="optional"/>
			<xs:attribute type="xs:string" name="codonNumbers" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="hvrVariants">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="hvrVariant" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hvrVariant">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="beads"/>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="variantId" use="optional"/>
			<xs:attribute type="xs:string" name="proteinSequences" use="optional"/>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="beads">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bead" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="bead">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="alleleName" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== ghsmith/hladpb1/hladpb1-imgtDb/data/hladpb1HypervariableRegion.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<reagentLots xmlns="http://pathology.emory.edu/hladpb1HypervariableRegion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="http://pathology.emory.edu/hladpb1HypervariableRegion.xsd">

  <reagentLot lotNumber="10">

    <hypervariableRegions>

      <hypervariableRegion hvrName="a" codonNumbers="8,9,11">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="VYG">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*15:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="VYL">
            <beads>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*06:01"/>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="3" proteinSequences="LFG">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*05:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="4" proteinSequences="VHL">
            <beads>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>
      
      <hypervariableRegion hvrName="b" codonNumbers="35,36">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="FV">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*06:01"/>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="YA">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*15:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="3" proteinSequences="FA">
            <beads>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="4" proteinSequences="LV">
            <beads>
              <bead alleleName="HLA-DPB1*05:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>
      
      <hypervariableRegion hvrName="c" codonNumbers="55,56,57">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="AAE">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*15:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="DED">
            <beads>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*06:01"/>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="3" proteinSequences="DEE">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="4" proteinSequences="EAE">
            <beads>
              <bead alleleName="HLA-DPB1*05:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>

      <hypervariableRegion hvrName="d" codonNumbers="65,69">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="IK">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*05:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="IE">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="3" proteinSequences="LK">
            <beads>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="4" proteinSequences="LE">
            <beads>
              <bead alleleName="HLA-DPB1*06:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="5" proteinSequences="LR">
            <beads>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*15:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>

      <hypervariableRegion hvrName="e" codonNumbers="76">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="V">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="M">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*05:01"/>
              <bead alleleName="HLA-DPB1*06:01"/>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*15:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="3" proteinSequences="I">
            <beads>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>

      <hypervariableRegion hvrName="f" codonNumbers="84,85,86,87">
        <hvrVariants>
          <hvrVariant variantId="1" proteinSequences="DEAV">
            <beads>
              <bead alleleName="HLA-DPB1*01:01"/>
              <bead alleleName="HLA-DPB1*03:01"/>
              <bead alleleName="HLA-DPB1*05:01"/>
              <bead alleleName="HLA-DPB1*06:01"/>
              <bead alleleName="HLA-DPB1*09:01"/>
              <bead alleleName="HLA-DPB1*10:01"/>
              <bead alleleName="HLA-DPB1*11:01"/>
              <bead alleleName="HLA-DPB1*13:01"/>
              <bead alleleName="HLA-DPB1*14:01"/>
              <bead alleleName="HLA-DPB1*17:01"/>
              <bead alleleName="HLA-DPB1*19:01"/>
              <bead alleleName="HLA-DPB1*20:01"/>
            </beads>
          </hvrVariant>
          <hvrVariant variantId="2" proteinSequences="GGPM,VGPM">
            <beads>
              <bead alleleName="HLA-DPB1*02:01"/>
              <bead alleleName="HLA-DPB1*04:01"/>
              <bead alleleName="HLA-DPB1*04:02"/>
              <bead alleleName="HLA-DPB1*15:01"/>
              <bead alleleName="HLA-DPB1*18:01"/>
              <bead alleleName="HLA-DPB1*23:01"/>
              <bead alleleName="HLA-DPB1*28:01"/>
            </beads>
          </hvrVariant>
        </hvrVariants>
      </hypervariableRegion>
    </hypervariableRegions>
  
  </reagentLot>
  
</reagentLots>
